Add as env variable

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,20 +27,21 @@ jobs:
           cd build/
           ctest -E system --output-on-failure
           cd ..
-      - name: Run Coverage
+      - name: Check Coverage
+        env:
+          MIN_COVERAGE: 100
+          EXCLUDE: ("*test*" "*CMakeCCompilerId*" "*mocks*" "**/*test*")
         run: |
           make -C build/ coverage
-          declare -a filters=("*test*" "*CMakeCCompilerId*" "*mocks*" "**/*test*")
-          for i in "${filters[@]}"
+          for i in "${EXCLUDE[@]}"
           do
-            lcov --rc lcov_branch_coverage=1 --remove build/coverage.info '$i' --output-file build/coverage.info
+            lcov --rc lcov_branch_coverage=1 --remove build/coverage.info $i --output-file build/coverage.info
           done
           lcov --rc lcov_branch_coverage=1 --list build/coverage.info
-      - name: Check Coverage
-        uses: ChicagoFlutter/lcov-cop@v1.0.2
-        with:
-          path: "build/coverage.info"
-          min_coverage: 100
+          CODE_COVERAGE=$(lcov --list ${LCOV_PATH} | sed -n "s/.*Total:|\([^%]*\)%.*/\1/p")
+          echo "Minumum Coverage Required: ${MIN_COVERAGE}%"
+          echo "Current Code Coverage: ${CODE_COVERAGE}%"
+          if (( $(echo "$CODE_COVERAGE < $2" | bc) )); then exit 1; fi
   complexity:
     runs-on: ubuntu-latest
     steps:
