Update default variable

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -15,11 +15,10 @@ on:
         required: false
 
 env:
-  repository_name: "coreMQTT"
-  repository_compressed_name: coreMQTT-${{ github.event.inputs.version_number }}
-  repository_zip_name: coreMQTT-${{ github.event.inputs.version_number }}.zip
+  repository_compressed_name: ${{ github.event.repository.name }}-${{ github.event.inputs.version_number }}
+  repository_zip_name: ${{ github.event.repository.name }}-${{ github.event.inputs.version_number }}.zip
   # Source folder list for version number updates
-  source_folder_list: "source test/cbmc test/unit-test"
+  source_folder_list: "source test"
 
 jobs:
   clean-existing-tag-and-release:
@@ -77,7 +76,7 @@ jobs:
             echo "${{ env.source_folder_list }}" | \
             xargs -n 1 sh -c \
             'find $1 -type f \( -name "*.c" -o -name "*.h" \) \
-            -exec sed -i -b -E "0,/^ \* ${{ env.repository_name }}/s/^ \* ${{ env.repository_name }}.*/ \* ${{ env.repository_name }} ${{ github.event.inputs.version_number }}/g" {} +'
+            -exec sed -i -b -E "0,/^ \* ${{ github.event.repository.name }}/s/^ \* ${{ github.event.repository.name }}.*/ \* ${{ github.event.repository.name }} ${{ github.event.inputs.version_number }}/g" {} +'
             git add .
             git commit -m '[AUTO][RELEASE]: Update version number in source files'
             git push -u origin ${{ github.event.inputs.version_number }}
@@ -97,7 +96,7 @@ jobs:
           git push -u origin ${{ github.event.inputs.version_number }}
 
       - name : Update MQTT version number macro
-        if: ${{ env.repository_name == 'coreMQTT' }}
+        if: ${{ github.event.repository.name == 'coreMQTT' }}
         run: |
           sed -i -b 's/^\#define MQTT_LIBRARY_VERSION .*/\#define MQTT_LIBRARY_VERSION    "${{ github.event.inputs.version_number }}"/g' source/include/core_mqtt.h
           git add .
@@ -118,7 +117,7 @@ jobs:
 
       - name: Tag Commit and Push to remote
         run: |
-          git tag ${{ github.event.inputs.version_number }} -a -m "${{ env.repository_name }} Library ${{ github.event.inputs.version_number }}"
+          git tag ${{ github.event.inputs.version_number }} -a -m "${{ github.event.repository.name }} Library ${{ github.event.inputs.version_number }}"
           git push origin --tags
 
       - name: Verify tag on remote
@@ -141,17 +140,17 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.event.inputs.version_number }}
-          path: ${{ env.repository_name }}
+          path: ${{ github.event.repository.name }}
           submodules: recursive
 
       - name: Checkout disabled submodules
         run: |
-          cd ${{ env.repository_name }}
+          cd ${{ github.event.repository.name }}
           git submodule update --init --checkout --recursive
 
       - name: Create ZIP
         run: |
-          zip -r ${{ env.repository_zip_name }} ${{ env.repository_name }} -x "*.git*"
+          zip -r ${{ env.repository_zip_name }} ${{ github.event.repository.name }} -x "*.git*"
           ls ./
 
       - name: Validate created ZIP
@@ -161,24 +160,24 @@ jobs:
           cd zip-check
           unzip ${{ env.repository_zip_name }} -d ${{ env.repository_compressed_name }}
           ls ${{ env.repository_compressed_name }}
-          diff -r -x "*.git*" ${{ env.repository_compressed_name }}/${{ env.repository_name }}/ ../${{ env.repository_name }}/
+          diff -r -x "*.git*" ${{ env.repository_compressed_name }}/${{ github.event.repository.name }}/ ../${{ github.event.repository.name }}/
           cd ../
 
       - name: Check version number in source files
         run: |
-          cd zip-check/${{ env.repository_compressed_name }}/${{ env.repository_name }}
+          cd zip-check/${{ env.repository_compressed_name }}/${{ github.event.repository.name }}
 
           echo "${{ env.source_folder_list }}" | \
           xargs -n 1 sh -c 'find $1 -type f \( -name "*.c" -o -name "*.h" \)' | \
-          xargs -I{} grep -l -x " \* ${{ env.repository_name }}.*" {} | \
+          xargs -I{} grep -l -x " \* ${{ github.event.repository.name }}.*" {} | \
           xargs -I{} sh -c \
-          'grep -x " \* ${{ env.repository_name }} ${{ github.event.inputs.version_number }}" {} && \
-          echo {} : match ${{ env.repository_name }} ${{ github.event.inputs.version_number }} || \
-          { echo "{} : ${{ env.repository_name }} ${{ github.event.inputs.version_number }} not found"; exit 255; }'
+          'grep -x " \* ${{ github.event.repository.name }} ${{ github.event.inputs.version_number }}" {} && \
+          echo {} : match ${{ github.event.repository.name }} ${{ github.event.inputs.version_number }} || \
+          { echo "{} : ${{ github.event.repository.name }} ${{ github.event.inputs.version_number }} not found"; exit 255; }'
 
       - name: Check version number in doxygen
         run: |
-          cd zip-check/${{ env.repository_compressed_name }}/${{ env.repository_name }}
+          cd zip-check/${{ env.repository_compressed_name }}/${{ github.event.repository.name }}
 
           # find "PROJECT_NUMBER = <version_number>" and compare the <version_number> with input version number
           DOXYGEN_VERSION_NUMBER=$(grep -x "[ ]*PROJECT_NUMBER[ ]*=[ ]*[^ ]*[ ]*" docs/doxygen/config.doxyfile | awk -F= '{gsub(" ","",$2); print $2 }');
@@ -188,7 +187,7 @@ jobs:
 
       - name: Check version number in manifest.yml
         run: |
-          cd zip-check/${{ env.repository_compressed_name }}/${{ env.repository_name }}
+          cd zip-check/${{ env.repository_compressed_name }}/${{ github.event.repository.name }}
 
           # find the first occurence of "version: <version_number>" and comare the <version_number> with input version number
           MANIFEST_VESION_NUMBER=$( grep -m 1 -E "^version:[ ]*\".*\"[ ]*" manifest.yml | awk -F: '{ gsub(" ","",$2); gsub("\"","",$2); print $2 }' ); \
@@ -197,9 +196,9 @@ jobs:
           || { echo "manifest.yml : $MANIFEST_VESION_NUMBER doesn't match ${{ github.event.inputs.version_number }}"; exit 255; }
 
       - name: Check MQTT version number macro in header file
-        if: ${{ env.repository_name == 'coreMQTT' }}
+        if: ${{ github.event.repository.name == 'coreMQTT' }}
         run: |
-          cd zip-check/${{ env.repository_compressed_name }}/${{ env.repository_name }}
+          cd zip-check/${{ env.repository_compressed_name }}/${{ github.event.repository.name }}
 
           # find "#define MQTT_LIBRARY_VERSION <version_number>" in core_mqtt.h and compare the <version_number> with input version number
           MACRO_VERSION_NUMBER=$(grep -x "^\#define[ ]*MQTT_LIBRARY_VERSION[ ]*\".*\"[ ]*" source/include/core_mqtt.h | awk '{gsub("\"","",$3); print $3 }'); \
@@ -209,7 +208,7 @@ jobs:
 
       - name: Build
         run: |
-          cd zip-check/${{ env.repository_compressed_name }}/${{ env.repository_name }}
+          cd zip-check/${{ env.repository_compressed_name }}/${{ github.event.repository.name }}
           sudo apt-get install -y lcov
           cmake -S test -B build/ \
           -G "Unix Makefiles" \
@@ -220,7 +219,7 @@ jobs:
 
       - name: Test
         run: |
-          cd zip-check/${{ env.repository_compressed_name }}/${{ env.repository_name }}/build/
+          cd zip-check/${{ env.repository_compressed_name }}/${{ github.event.repository.name }}/build/
           ctest -E system --output-on-failure
           cd ..
 
@@ -258,7 +257,7 @@ jobs:
         with:
           tag_name: ${{ github.event.inputs.version_number }}
           release_name: ${{ github.event.inputs.version_number }}
-          body: Release ${{ github.event.inputs.version_number }} of the ${{ env.repository_name }} Library.
+          body: Release ${{ github.event.inputs.version_number }} of the ${{ github.event.repository.name }} Library.
           draft: false
           prerelease: false
 
